"use client";

import { useState } from "react";
import { Loader2, Trash, Play, Pause } from "lucide-react";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { 
  bulkActivateRecurringExpenses, 
  bulkDeactivateRecurringExpenses, 
  bulkHardDeleteRecurringExpenses 
} from "@/app/actions/recurring.actions";
import { toast } from "sonner";

interface RecurringBulkActionBarProps {
  selectedCount: number;
  selectedIds: string[];
  orgSlug: string;
  onDismiss: () => void;
}

export function RecurringBulkActionBar({
  selectedCount,
  selectedIds,
  orgSlug,
  onDismiss,
}: RecurringBulkActionBarProps) {
  const [isLoading, setIsLoading] = useState(false);

  if (selectedCount === 0) return null;

  const handleActivate = async () => {
    setIsLoading(true);
    try {
      await bulkActivateRecurringExpenses(orgSlug, selectedIds);
      toast.success(`Activated ${selectedCount} recurring expenses`);
      onDismiss();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to activate");
    } finally {
      setIsLoading(false);
    }
  };

  const handleDeactivate = async () => {
    setIsLoading(true);
    try {
      await bulkDeactivateRecurringExpenses(orgSlug, selectedIds);
      toast.success(`Deactivated ${selectedCount} recurring expenses`);
      onDismiss();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to deactivate");
    } finally {
      setIsLoading(false);
    }
  };

  const handleDelete = async () => {
    setIsLoading(true);
    try {
      await bulkHardDeleteRecurringExpenses(orgSlug, selectedIds);
      toast.success(`Permanently deleted ${selectedCount} recurring expenses`);
      onDismiss();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to delete");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="fixed bottom-24 left-1/2 -translate-x-1/2 z-50 flex items-center gap-4 rounded-full bg-zinc-900 px-6 py-3 shadow-xl text-white">
      <span className="text-sm font-medium whitespace-nowrap">
        {selectedCount} selected
      </span>
      
      <div className="h-4 w-px bg-zinc-700 mx-1" />

      <div className="flex items-center gap-2">
        <Button
          variant="outline"
          size="sm"
          disabled={isLoading}
          onClick={handleActivate}
          className="h-8 border-zinc-700 bg-zinc-800 text-xs text-white hover:bg-zinc-700 hover:text-white"
        >
          {isLoading ? <Loader2 className="mr-1 h-3 w-3 animate-spin" /> : <Play className="mr-1 h-3 w-3" />}
          Activate
        </Button>

        <Button
          variant="outline"
          size="sm"
          disabled={isLoading}
          onClick={handleDeactivate}
          className="h-8 border-zinc-700 bg-zinc-800 text-xs text-white hover:bg-zinc-700 hover:text-white"
        >
          {isLoading ? <Loader2 className="mr-1 h-3 w-3 animate-spin" /> : <Pause className="mr-1 h-3 w-3" />}
          Deactivate
        </Button>

        <AlertDialog>
          <AlertDialogTrigger asChild>
            <Button
              variant="destructive"
              size="icon"
              disabled={isLoading}
              className="h-8 w-8 ml-1 rounded-full bg-red-600 hover:bg-red-700 border-0"
            >
              {isLoading ? (
                <Loader2 className="h-3 w-3 animate-spin text-white" />
              ) : (
                <Trash className="h-3 w-3 text-white" />
              )}
            </Button>
          </AlertDialogTrigger>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
              <AlertDialogDescription>
                This action cannot be undone. This will permanently delete {selectedCount} recurring expense(s) from the database. Existing transactions generated by these expenses will remain intact.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancel</AlertDialogCancel>
              <AlertDialogAction onClick={handleDelete} className="bg-red-600 hover:bg-red-700 text-white">
                Delete Permanently
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </div>
    </div>
  );
}
